name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn joblib numpy pytest pre-commit ruff black

      - name: Lint (pre-commit)
        run: python -m pre_commit run --all-files --show-diff-on-failure

      - name: Run tests
        run: python -m pytest -q
